services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /frontend
    command: sh dockerEntryPoint.sh
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/mydb?schema=public
    volumes:
      - source: .
        target: /frontend
        type: bind

      - source: frontend
        target: /frontend/node_modules
        type: volume
    ports:
      - target: 3000
        published: 3000
        protocol: tcp

      - target: 9229
        published: 9229
        protocol: tcp
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  frontend:
  postgres_data: